# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_code', models.CharField(max_length=256L)),
                ('sales_order_no', models.IntegerField()),
                ('po_no', models.IntegerField()),
                ('item_desc', models.CharField(max_length=256L)),
                ('unit', models.CharField(max_length=256L)),
                ('dispatch_quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transport_state', django_fsm.FSMField(choices=[('proposed loading time', 'proposed loading time'), ('confirmed loading time', 'confirmed loading time'), ('actual loading time', 'actual loading time'), ('leaving time', 'leaving time'), ('unloading time', 'unloading time'), ('completed', 'completed')], default='proposed loading time', max_length=50, protected=True, verbose_name='Transport State')),
                ('driver_select_state', django_fsm.FSMField(choices=[('set volume', 'set volume'), ('set driver', 'set driver'), ('revise volumes', 'revise volumes'), ('confirm driver', 'confirm driver'), ('completed', 'completed')], default='set volume', max_length=50, protected=True, verbose_name='Driver State')),
                ('release_order', models.CharField(max_length=256L)),
                ('waybill_ref', models.CharField(max_length=256L)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('waybill_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cosignee', models.CharField(default='', max_length=256L)),
                ('proposed_loading_time', models.TimeField(blank=True, null=True)),
                ('loading_time_start', models.TimeField(blank=True, null=True)),
                ('loading_time_end', models.TimeField(blank=True, null=True)),
                ('unloading_time_start', models.TimeField(blank=True, null=True)),
                ('unloading_time_end', models.TimeField(blank=True, null=True)),
                ('leaving_time', models.TimeField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('waybill_doc_signed1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('waybill_doc_signed2', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256L)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256L)),
                ('warehouse_type', models.CharField(choices=[('UNICEF_WH', 'Unicef Warehouse'), ('PARTNER_WH', 'Partner Warehouse')], max_length=256L)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location')),
            ],
        ),
    ]
