# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_code', models.CharField(max_length=256L)),
                ('sales_order_no', models.IntegerField()),
                ('po_no', models.IntegerField()),
                ('item_desc', models.CharField(max_length=256L)),
                ('unit', models.CharField(max_length=256L)),
                ('dispatch_quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('release_order_id', models.CharField(max_length=256L)),
                ('waybill_ref', models.CharField(max_length=256L)),
                ('reference_number', models.CharField(max_length=256L)),
                ('waybill_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256L)),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cosignee', models.CharField(max_length=256L)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('loading_time', models.TimeField(default=django.utils.timezone.now)),
                ('unloading_time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('ONGOING', 'Ongoing'), ('DELIVERED', 'Delivered')], max_length=256L)),
                ('waybill_signed', models.BooleanField()),
                ('RO_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.ReleaseOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256L)),
                ('type', models.CharField(choices=[('UNICEF_WH', 'Unicef Warehouse'), ('PARTNER_WH', 'Partner Warehouse')], max_length=256L)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location')),
            ],
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination warehouse+', to='transport.Warehouse'),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
    ]
