# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('plate_number', models.CharField(max_length=256L)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_code', models.CharField(max_length=256)),
                ('sales_order_no', models.IntegerField()),
                ('po_no', models.IntegerField()),
                ('item_desc', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
                ('dispatch_quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transport_state', django_fsm.FSMField(choices=[('Proposed Loading Time', 'Proposed Loading Time'), ('Confirmed Loading Time', 'Confirmed Loading Time'), ('Actual Loading Time', 'Actual Loading Time'), ('Leaving Time', 'Leaving Time'), ('Unloading Time', 'Unloading Time'), ('Completed', 'Completed')], default='Proposed Loading Time', max_length=50, protected=True, verbose_name='Transport State')),
                ('driver_select_state', django_fsm.FSMField(choices=[('Set volume', 'Set volume'), ('set driver', 'set driver'), ('revise volumes', 'revise volumes'), ('confirm driver', 'confirm driver'), ('completed', 'completed')], default='Set volume', max_length=50, protected=True, verbose_name='Driver State')),
                ('release_order', models.CharField(max_length=256)),
                ('waybill_ref', models.CharField(max_length=256)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('waybill_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('proposed_loading_time', models.TimeField(blank=True, null=True)),
                ('loading_time_start', models.TimeField(blank=True, null=True)),
                ('loading_time_end', models.TimeField(blank=True, null=True)),
                ('unloading_date', models.DateField(blank=True, null=True)),
                ('unloading_time_start', models.TimeField(blank=True, null=True)),
                ('unloading_time_end', models.TimeField(blank=True, null=True)),
                ('leaving_time', models.TimeField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('waybill_doc_signed1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('waybill_doc_signed2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cosignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cosignee+', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination warehouse+', to='locations.Location')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.Driver')),
                ('focal_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Focal Point+', to=settings.AUTH_USER_MODEL)),
                ('loading_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading warehouse+', to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Section'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transporter Company+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='release_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.ReleaseOrder'),
        ),
        migrations.AddField(
            model_name='driver',
            name='v_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.VehicleType'),
        ),
    ]
