# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-25 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('transport', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseorder',
            name='cosignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cosignee+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination warehouse+', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.Driver'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='focal_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Focal Point+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='loading_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading warehouse+', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transporter Company+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='release_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.ReleaseOrder'),
        ),
        migrations.AddField(
            model_name='driver',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='v_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.VehicleType'),
        ),
    ]
