# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0001_initial'),
        ('drivers', '0002_auto_20170904_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Warehouse Focal Point+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination warehouse+', to='transport.Warehouse'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='focal_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Focal Point+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='loading_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading warehouse+', to='transport.Warehouse'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Section'),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transporter Company+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='release_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.ReleaseOrder'),
        ),
    ]
