# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_transport_id'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
    ]
