# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20170904_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseorder',
            name='unloading_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
