# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_releaseorder_unloading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseorder',
            name='unloading_date',
            field=models.DateField(),
        ),
    ]
