# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transportdetail_sub_waybill_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='type',
            new_name='warehouse_type',
        ),
    ]
