# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20170908_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseorder',
            name='cosignee',
            field=models.CharField(default='', max_length=256L),
        ),
    ]
