# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20170707_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetail',
            name='location',
        ),
    ]
