# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0006_remove_transportdetail_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releaseorder',
            old_name='release_order_id',
            new_name='release_order',
        ),
        migrations.RenameField(
            model_name='transportdetail',
            old_name='loading_time',
            new_name='proposed_loading_time',
        ),
        migrations.RenameField(
            model_name='transportdetail',
            old_name='RO_id',
            new_name='release_order',
        ),
        migrations.RenameField(
            model_name='transportdetail',
            old_name='unloading_time',
            new_name='unloading_time_start',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='cosignee',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='focal_point',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='loading_warehouse',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='section',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='sub_waybill_ref',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='transporter',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='waybill_signed',
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='cosignee',
            field=models.CharField(default='', max_length=256L),
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='destination_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination warehouse+', to='transport.Warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='focal_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Focal Point+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='loading_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loading warehouse+', to='transport.Warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transport.Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transporter Company+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='loading_time_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='loading_time_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='unloading_time_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
