# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20170908_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseorder',
            name='cosignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cosignee+', to=settings.AUTH_USER_MODEL),
        ),
    ]
