# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 14:08
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20170707_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='driver_select_state',
            field=django_fsm.FSMField(choices=[('set volume', 'set volume'), ('set_drivers', 'set_drivers'), ('revise volumes', 'revise volumes'), ('confirm driver', 'confirm driver'), ('completed', 'completed')], default='set volume', max_length=50, protected=True, verbose_name='Driver State'),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='transport_state',
            field=django_fsm.FSMField(choices=[('proposed loading time', 'proposed loading time'), ('confirmed loading time', 'confirmed loading time'), ('actual loading time', 'actual loading time'), ('leaving time', 'leaving time'), ('unloading time', 'unloading time'), ('completed', 'completed')], default='proposed loading time', max_length=50, protected=True, verbose_name='Transport State'),
        ),
    ]
