# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_auto_20170710_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
