# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20170710_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetail',
            name='loading_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='loading_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='unloading_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='unloading_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
