# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20170711_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetail',
            name='proposed_loading_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
