# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20170711_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetail',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='releaseorder',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
