# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_auto_20170712_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='waybill_doc_signed1',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='waybill_doc_signed2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
