# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_auto_20170712_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetail',
            name='driver_select_state',
            field=django_fsm.FSMField(choices=[('set volume', 'set volume'), ('set driver', 'set driver'), ('revise volumes', 'revise volumes'), ('confirm driver', 'confirm driver'), ('completed', 'completed')], default='set volume', max_length=50, protected=True, verbose_name='Driver State'),
        ),
    ]
