# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0014_auto_20170713_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Warehouse Focal Point+', to=settings.AUTH_USER_MODEL),
        ),
    ]
