# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-26 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Risk Rating'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='shared_partner',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('with UNDP', 'with UNDP'), ('with UNFPA', 'with UNFPA'), ('with UNDP & UNFPA', 'with UNDP & UNFPA')], default='No', help_text='Partner shared with UNDP or UNFPA?', max_length=50),
        ),
    ]
