# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180226_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
