# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-12 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0003_auto_20180307_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('PCA', 'Programme Cooperation Agreement'), ('SSFA', 'Small Scale Funding Agreement'), ('MOU', 'Memorandum of Understanding'), ('IC', 'Institutional Contract'), ('AWP', 'Work Plan')], max_length=10)),
                ('agreement_number', models.CharField(blank=True, max_length=45L, verbose_name='Reference Number')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('signed_by_unicef_date', models.DateField(blank=True, null=True)),
                ('signed_by_partner_date', models.DateField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization')),
                ('partner_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerStaffMember', verbose_name='Signed by partner')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_pcas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_type', models.CharField(blank=True, choices=[('PD', 'Programme Document'), ('SHPD', 'Simplified Humanitarian Programme Document'), ('AWP', 'Cash Transfers to Government'), ('SSFA', 'SSFA TOR'), ('IC', 'IC TOR')], default='PD', max_length=255, null=True, verbose_name='Document type')),
                ('result_structure', models.CharField(blank=True, help_text='Which result structure does this partnership report under?', max_length=32, null=True)),
                ('number', models.CharField(blank=True, max_length=45L, null=True, verbose_name='Reference Number')),
                ('title', models.CharField(max_length=256L)),
                ('project_type', models.CharField(blank=True, choices=[('Bulk Procurement', 'Bulk Procurement'), ('Construction Project', 'Construction Project')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled')], default='in_process', help_text='In Process = In discussion with partner, Active = Currently ongoing, Implemented = completed, Cancelled = cancelled or not approved', max_length=32)),
                ('start_date', models.DateField(blank=True, help_text='The date the Intervention will start', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The date the Intervention will end', null=True)),
                ('initiation_date', models.DateField(help_text='The date the partner submitted complete partnership documents to Unicef', verbose_name='Submission Date')),
                ('submission_date', models.DateField(blank=True, help_text='The date the documents were submitted to the PRC', null=True, verbose_name='Submission Date to PRC')),
                ('review_date', models.DateField(blank=True, help_text='The date the PRC reviewed the partnership', null=True, verbose_name='Review date by PRC')),
                ('signed_by_unicef_date', models.DateField(blank=True, null=True)),
                ('signed_by_partner_date', models.DateField(blank=True, null=True)),
                ('fr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('planned_visits', models.IntegerField(default=0)),
                ('sectors', models.CharField(blank=True, max_length=255, null=True)),
                ('current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='partners.Agreement')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.PartnerOrganization')),
                ('partner_focal_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_partnerships', to='partners.PartnerStaffMember')),
                ('partner_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_partnerships', to='partners.PartnerStaffMember', verbose_name='Signed by partner')),
                ('unicef_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_partnerships', to=settings.AUTH_USER_MODEL, verbose_name='Signed by')),
                ('unicef_managers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Unicef focal points')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
    ]
