# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-28 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20180328_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pca',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='pca',
            old_name='start_date',
            new_name='start',
        ),
    ]
