# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-28 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20180328_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pca',
            old_name='result_structure',
            new_name='country_programme',
        ),
    ]
