# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20180328_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='end',
            field=models.DateField(blank=True, help_text='The date the Intervention will end', null=True, verbose_name='Partnership end date'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='start',
            field=models.DateField(blank=True, help_text='The date the Intervention will start', null=True, verbose_name='Partnership start date'),
        ),
    ]
