# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_auto_20180412_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='phone',
            field=models.CharField(max_length=64),
        ),
    ]
