# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_auto_20180605_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='partner_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Risk Rating'),
        ),
    ]
