# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='transport_id',
        ),
    ]
