# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-14 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationtype',
            old_name='type',
            new_name='name',
        ),
    ]
