# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180414_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
