# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-17 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_p_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name', 'type', 'p_code')]),
        ),
    ]
