# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(max_length=10)),
                ('unit_weight', models.DecimalField(decimal_places=2, help_text='KG', max_digits=3)),
                ('unit_volume', models.DecimalField(decimal_places=2, help_text='M3', max_digits=3)),
                ('quantity_in_stock', models.PositiveIntegerField()),
            ],
        ),
    ]
