# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='number',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='unit_of_measure',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='unit_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='M3', max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='KG', max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
