# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_auto_20180226_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='$', max_digits=10, null=True),
        ),
    ]
