# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_supplyitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='price',
            field=models.FloatField(blank=True, help_text='$', null=True),
        ),
    ]
