# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_auto_20180413_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='price',
            field=models.FloatField(blank=True, help_text='$', null=True, verbose_name='Unit price'),
        ),
    ]
