# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_auto_20180426_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
        ),
    ]
