# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_auto_20180605_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('expected_amount', models.FloatField(blank=True, help_text='$', null=True, verbose_name='Unit price')),
            ],
        ),
    ]
