# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180307_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
