# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-31 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180517_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
