# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('to_review', models.BooleanField(default=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('to_validate', models.BooleanField(default=False)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('to_approve', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistributionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('emergency_request', 'Emergency Request'), ('pd_request', 'PD Request')], max_length=50, null=True)),
                ('target_population', models.IntegerField(blank=True, null=True, verbose_name='No. of beneficiaries covered')),
                ('quantity_requested', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity required for this location')),
                ('date_required_by', models.DateField(blank=True, null=True)),
                ('date_distributed_by', models.DateField(blank=True, null=True, verbose_name='planned distribution date')),
                ('quantity_received', models.PositiveIntegerField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('quantity_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('date_distributed', models.DateField(blank=True, null=True)),
                ('quantity_distributed', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='PD Quantity')),
                ('wave_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('date_required_by', models.DateField(blank=True, null=True)),
                ('target_population', models.IntegerField(blank=True, null=True, verbose_name='Max No. of beneficiaries covered')),
                ('covered_per_item', models.IntegerField(blank=True, null=True, verbose_name='Beneficiaries covered per item')),
            ],
        ),
        migrations.CreateModel(
            name='WavePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('quantity_required', models.PositiveIntegerField(blank=True, help_text='Quantity required for this wave', null=True)),
                ('date_required_by', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
