# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='covered_per_item',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='target_population',
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='covered_per_item',
            field=models.IntegerField(default=0, help_text='Beneficiaries covered per item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=0, help_text='Quantity required for this location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='target_population',
            field=models.IntegerField(default=0, help_text='No. of beneficiaries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='quantity',
            field=models.PositiveIntegerField(help_text='PD Quantity'),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planning.Section'),
            preserve_default=False,
        ),
    ]
