# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('supplies', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveplan',
            name='supply_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyItem'),
        ),
        migrations.AddField(
            model_name='waveplan',
            name='supply_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlan'),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyItem'),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='supply_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlan'),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization'),
        ),
    ]
