# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('supplies', '0002_auto_20171115_2112'),
        ('planning', '0002_auto_20171115_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='PD Quantity')),
                ('target_population', models.IntegerField(blank=True, help_text='No. of beneficiaries', null=True)),
                ('covered_per_item', models.IntegerField(blank=True, help_text='Beneficiaries covered per item', null=True)),
                ('quantity_requested', models.PositiveIntegerField(blank=True, help_text='Quantity required for this location', null=True)),
                ('date_required_by', models.DateField(blank=True, null=True)),
                ('date_distributed_by', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyItem')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('supply_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlan')),
            ],
        ),
        migrations.RemoveField(
            model_name='distributionplan',
            name='item',
        ),
        migrations.RemoveField(
            model_name='distributionplan',
            name='site',
        ),
        migrations.RemoveField(
            model_name='distributionplan',
            name='supply_plan',
        ),
        migrations.DeleteModel(
            name='DistributionPlan',
        ),
        migrations.CreateModel(
            name='DistributionPlanItem',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('planning.supplyplanitem',),
        ),
        migrations.CreateModel(
            name='DistributionPlan',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('planning.supplyplan',),
        ),
    ]
