# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20180225_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplyplanitem',
            old_name='date_required_by',
            new_name='date_required_by_1',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_number',
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='date_required_by_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='date_required_by_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='date_required_by_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_number_1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_number_2',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_number_3',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_number_4',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_quantity_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_quantity_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_quantity_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplanitem',
            name='wave_quantity_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
