# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20171115_2112'),
        ('planning', '0005_supplyplan_partnership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(blank=True, help_text='Quantity required for this wave', null=True)),
                ('date_required_by', models.DateField(blank=True, null=True)),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyItem')),
                ('supply_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlan')),
            ],
        ),
    ]
