# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20180226_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32L),
        ),
    ]
