# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_auto_20180307_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32L),
        ),
    ]
