# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20171130_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplanitem',
            name='purpose',
            field=models.CharField(blank=True, choices=[('emergency_request', 'Emergency Request'), ('pd_request', 'PD Request')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
            preserve_default=False,
        ),
    ]
