# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20180307_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization'),
        ),
    ]
