# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_auto_20171130_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplanitem',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlan'),
            preserve_default=False,
        ),
    ]
