# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_auto_20180307_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
        ),
    ]
