# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-12 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_auto_20180307_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Planned by'),
        ),
        migrations.AlterField(
            model_name='supplyplanitem',
            name='date_required_by_1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supplyplanitem',
            name='wave_number_1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='supplyplanitem',
            name='wave_quantity_1',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
