# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_auto_20171201_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplanitem',
            name='date_distributed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplanitem',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplanitem',
            name='quantity_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplanitem',
            name='quantity_distributed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplanitem',
            name='quantity_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
