# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_auto_20180312_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='partnership_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='partnership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
