# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_auto_20180312_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='planning.DistributionPlan'),
        ),
    ]
