# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_auto_20180328_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlanItem'),
        ),
    ]
