# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_auto_20180329_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveplan',
            name='supply_plan_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlanItem'),
            preserve_default=False,
        ),
    ]
