# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_waveplan_supply_plan_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waveplan',
            name='supply_item',
        ),
        migrations.RemoveField(
            model_name='waveplan',
            name='supply_plan_item',
        ),
        migrations.AlterField(
            model_name='waveplan',
            name='supply_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlanItem'),
        ),
    ]
