# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_auto_20180410_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.WavePlan'),
        ),
    ]
