# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_auto_20180410_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerStaffMember'),
        ),
    ]
