# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_auto_20180410_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='partnership',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partnership/Reference Number'),
        ),
    ]
