# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20180328_0849'),
        ('planning', '0020_auto_20180410_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='pca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PCA', verbose_name='Partnership/Reference Number'),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner Organization'),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='partnership',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
    ]
