# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0021_auto_20180410_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='purpose',
            field=models.CharField(blank=True, choices=[('emergency_request', 'Emergency Request'), ('pd_request', 'PD Request')], default='pd_request', max_length=50, null=True),
        ),
    ]
