# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_auto_20180410_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
