# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0023_distributionplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyplan',
            name='partnership_end_date',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='partnership_start_date',
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='to_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='to_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='to_validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='validation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
