# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0024_auto_20180410_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='to_review',
            field=models.BooleanField(default=False),
        ),
    ]
