# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0025_auto_20180410_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='to_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
