# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 14:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0026_auto_20180410_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='pca',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='partner_name', chained_model_field='partner__name', null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PCA', verbose_name='Partnership/Reference Number'),
        ),
    ]
