# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0027_auto_20180410_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='approval_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='review_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='pca',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='partner__name', chained_model_field='partner_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PCA', verbose_name='Partnership/Reference Number'),
        ),
    ]
