# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0028_auto_20180410_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='approval_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='review_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='validation_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
