# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0029_auto_20180410_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplanitem',
            name='supply_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_plans', to='planning.SupplyPlan'),
        ),
        migrations.AlterField(
            model_name='waveplan',
            name='date_required_by',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='waveplan',
            name='quantity_required',
            field=models.PositiveIntegerField(help_text='Quantity required for this wave', null=True),
        ),
        migrations.AlterField(
            model_name='waveplan',
            name='supply_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_plans_waves', to='planning.SupplyPlanItem'),
        ),
        migrations.AlterField(
            model_name='waveplan',
            name='wave_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
    ]
