# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-14 19:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0031_auto_20180413_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='contact_person',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='partner', chained_model_field='partner', null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerStaffMember'),
        ),
    ]
