# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0033_auto_20180414_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPlanWave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True)),
                ('quantity_required', models.PositiveIntegerField(help_text='Quantity required for this wave', null=True)),
                ('date_required_by', models.DateField(null=True)),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items_waves', to='planning.SupplyPlanItem')),
            ],
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.WavePlan'),
        ),
    ]
