# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0034_auto_20180414_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplanwave',
            name='wave_number',
        ),
        migrations.AddField(
            model_name='distributionplanitem',
            name='wave_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='distributionplanwave',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='planning.DistributionPlanItem'),
            preserve_default=False,
        ),
    ]
