# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0037_auto_20180416_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplanwave',
            name='date_distributed_by',
            field=models.DateField(blank=True, null=True, verbose_name='planned distribution date'),
        ),
    ]
