# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0038_distributionplanwave_date_distributed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='wave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.WavePlan'),
        ),
    ]
