# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0039_auto_20180416_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPlanItemReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True)),
                ('quantity_received', models.PositiveIntegerField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('quantity_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('date_distributed', models.DateField(blank=True, null=True)),
                ('quantity_distributed', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='planning.DistributionPlan')),
                ('wave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.DistributionPlanItem')),
            ],
        ),
    ]
