# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0040_distributionplanitemreceived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplanitemreceived',
            name='quantity_balance',
        ),
    ]
