# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0041_remove_distributionplanitemreceived_quantity_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionitemrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='distributionitemrequest',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='distributionitemrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='distributionitemrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='distributionitemrequest',
            name='validated_by',
        ),
        migrations.DeleteModel(
            name='DistributionItemRequest',
        ),
    ]
