# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0042_auto_20180416_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='wave_number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='distributionplanitemreceived',
            name='wave_number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True),
        ),
    ]
