# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20180417_0752'),
        ('planning', '0043_auto_20180418_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='distributeditem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributed', to='planning.DistributionPlan'),
        ),
        migrations.AddField(
            model_name='distributeditem',
            name='sites',
            field=models.ManyToManyField(null=True, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='distributeditem',
            name='supply_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributed_items', to='planning.SupplyPlanItem'),
        ),
    ]
