# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-06 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0044_auto_20180426_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditem',
            name='quantity_distributed_per_site',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distributeditem',
            name='sites',
            field=models.ManyToManyField(to='locations.Location'),
        ),
    ]
