# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-07 07:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_auto_20180417_0752'),
        ('planning', '0046_auto_20180506_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity_assessment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('quality_assessment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.DistributionPlan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
