# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-07 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_auto_20180417_0752'),
        ('planning', '0047_tpmrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributeditem',
            name='sites',
        ),
        migrations.AddField(
            model_name='distributeditem',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='cleared_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='to_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tpmrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
