# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0048_auto_20180507_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('cleared', 'Cleared'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
