# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0049_auto_20180507_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='delivery_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
