# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-07 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0050_distributionplan_delivery_expected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyplan',
            name='cleared',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='cleared_by',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='cleared_comments',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='cleared_date',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='to_cleared',
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='cleared_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='to_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
