# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0055_remove_distributeditem_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeditemsite',
            name='quantity_distributed_per_site',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
