# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-08 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0056_auto_20180508_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tpmrequest',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tpmrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='tpmrequest',
            name='site',
        ),
        migrations.DeleteModel(
            name='TPMRequest',
        ),
    ]
