# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0057_auto_20180508_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditemsite',
            name='tpm_visit',
            field=models.BooleanField(default=False, verbose_name='TPM Visit?'),
        ),
    ]
