# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0058_distributeditemsite_tpm_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeditemsite',
            name='tpm_visit',
            field=models.BooleanField(default=False, help_text='TPM visit for this location', verbose_name='TPM Visit?'),
        ),
    ]
