# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0059_auto_20180509_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditemsite',
            name='distribution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
