# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0060_distributeditemsite_distribution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
