# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 13:56
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0061_auto_20180509_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
