# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-14 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0063_auto_20180510_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='tpm_focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distributeditemsite',
            name='tpm_visit',
            field=models.BooleanField(default=False, help_text='SM visit for this location', verbose_name='SM Visit?'),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='delivery_location',
            field=models.ForeignKey(blank=True, help_text='Leave it empty if the same save the Site above', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to='locations.Location'),
        ),
    ]
