# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-14 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0064_auto_20180514_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplanwave',
            name='wave_number',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='tpm_focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='TPM focal point'),
        ),
    ]
