# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0065_auto_20180514_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplanwave',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='distributionplanwave',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='distributionplanwave',
            name='supply_item',
        ),
        migrations.AddField(
            model_name='distributionplanitemreceived',
            name='wave_number',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='DistributionPlanWave',
        ),
    ]
