# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0066_auto_20180514_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='planning.SupplyPlan'),
        ),
    ]
