# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0067_auto_20180518_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='item_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='item_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('submitted', 'Submitted/Plan completed'), ('reviewed', 'Reviewed'), ('cleared', 'Cleared'), ('approved', 'Approved'), ('received', 'Received'), ('completed', 'Distribution Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
