# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0068_auto_20180518_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='item_distributed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='item_received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
