# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0070_supplyplan_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditem',
            name='wave_number',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('submitted', 'Submitted/Plan completed'), ('reviewed', 'Reviewed'), ('cleared', 'Cleared'), ('approved', 'Approved'), ('received', 'All waves received'), ('completed', 'Distribution Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
