# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0071_auto_20180522_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditem',
            name='quantity_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
