# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0072_distributeditem_quantity_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanitem',
            name='date_distributed_by',
            field=models.DateField(null=True, verbose_name='planned distribution date'),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='date_required_by',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='quantity_requested',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantity required for this location'),
        ),
    ]
