# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-23 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0073_auto_20180523_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='date_required_by_1',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='date_required_by_2',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='date_required_by_3',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='date_required_by_4',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_number_1',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_number_2',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_number_3',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_number_4',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_quantity_1',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_quantity_2',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_quantity_3',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='wave_quantity_4',
        ),
    ]
