# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-24 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0074_auto_20180523_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='date_distributed',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='quantity_balance',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='quantity_distributed',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='quantity_received',
        ),
    ]
