# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0076_auto_20180525_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplanitem',
            name='delivery_expected_date',
            field=models.DateField(blank=True, help_text='To be defined UNICEF Supply Beirut focal point', null=True),
        ),
        migrations.AddField(
            model_name='distributionplanitem',
            name='to_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
