# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-28 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0077_auto_20180528_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditem',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.WavePlan'),
        ),
        migrations.AddField(
            model_name='distributionplanitemreceived',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planning.WavePlan'),
        ),
        migrations.AlterField(
            model_name='distributionplanitem',
            name='delivery_expected_date',
            field=models.DateField(blank=True, help_text='To be defined by UNICEF Supply Beirut focal point', null=True),
        ),
    ]
