# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0080_auto_20180529_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted/Plan completed'), ('reviewed', 'Reviewed'), ('cleared', 'Cleared'), ('approved', 'Approved'), ('received', 'All waves received'), ('completed', 'Distribution Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='approved',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='reviewed',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32),
        ),
    ]
