# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-30 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0081_auto_20180530_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='reviewed',
            field=models.NullBooleanField(default=None),
        ),
    ]
