# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0082_auto_20180530_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplan',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='cleared',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='reviewed',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='validated',
            field=models.NullBooleanField(default=None),
        ),
    ]
