# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-31 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_auto_20180426_1310'),
        ('planning', '0084_auto_20180531_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPlanWave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True)),
                ('date_required_by', models.DateField(null=True)),
                ('supply_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_plans_waves', to='planning.SupplyPlan')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyPlanWaveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='PD Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyItem')),
                ('plan_wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_plan_wave_items', to='planning.SupplyPlanWave')),
            ],
        ),
        migrations.AlterField(
            model_name='waveplan',
            name='supply_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_plan', to='planning.SupplyPlanItem'),
        ),
    ]
