# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-31 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_auto_20180412_1315'),
        ('locations', '0006_auto_20180417_0752'),
        ('supplies', '0008_auto_20180426_1310'),
        ('planning', '0085_auto_20180531_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPlanWave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wave_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('emergency_request', 'Emergency Request'), ('pd_request', 'PD Request')], default='pd_request', max_length=50, null=True)),
                ('date_required_by', models.DateField(null=True)),
                ('to_delivery', models.BooleanField(default=False)),
                ('delivery_expected_date', models.DateField(blank=True, help_text='To be defined by UNICEF Supply Beirut focal point', null=True)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerStaffMember')),
                ('delivery_site', models.ForeignKey(blank=True, help_text='Leave it empty if the same save the Site above', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_site', to='locations.Location')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_plans_waves', to='planning.DistributionPlan')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('wave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlanWave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistributionPlanWaveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(null=True, verbose_name='Quantity required')),
                ('target_population', models.IntegerField(blank=True, null=True, verbose_name='No. of beneficiaries covered')),
                ('date_distributed_by', models.DateField(null=True, verbose_name='planned distribution date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyItem')),
                ('plan_wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_plan_wave', to='planning.DistributionPlanWave')),
                ('wave_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.SupplyPlanWaveItem')),
            ],
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='wave_number',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Number of waves'),
        ),
    ]
