# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-31 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0087_auto_20180531_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanwave',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_waves', to='planning.DistributionPlan'),
        ),
        migrations.AlterField(
            model_name='distributionplanwaveitem',
            name='plan_wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_wave_items', to='planning.DistributionPlanWave'),
        ),
    ]
