# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-31 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0089_auto_20180531_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributeditem',
            name='wave_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributed_wave_item', to='planning.DistributionPlanWaveItem'),
        ),
        migrations.AlterField(
            model_name='distributionplanitemreceived',
            name='wave_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_wave_item', to='planning.DistributionPlanWaveItem'),
        ),
    ]
