# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0090_auto_20180531_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanwave',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Distribution site'),
        ),
    ]
