# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-02 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0091_auto_20180601_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditemsite',
            name='unicef_visit',
            field=models.BooleanField(default=False, help_text='UNICEF visit for this location', verbose_name='UNICEF Visit?'),
        ),
        migrations.AlterField(
            model_name='distributeditemsite',
            name='tpm_visit',
            field=models.BooleanField(default=False, help_text='TPM visit for this location', verbose_name='TPM Visit?'),
        ),
    ]
