# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0092_auto_20180602_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanwave',
            name='date_required_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distributionplanwave',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Distribution site'),
        ),
    ]
