# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0093_auto_20180603_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanwaveitem',
            name='date_distributed_by',
            field=models.DateField(blank=True, null=True, verbose_name='planned distribution date'),
        ),
    ]
