# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-03 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0095_auto_20180603_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='site',
        ),
        migrations.RemoveField(
            model_name='distributionplanitem',
            name='wave',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplyplanitem',
            name='supply_plan',
        ),
        migrations.RemoveField(
            model_name='waveplan',
            name='supply_plan',
        ),
        migrations.RemoveField(
            model_name='distributeditem',
            name='wave',
        ),
        migrations.RemoveField(
            model_name='distributionplanitemreceived',
            name='wave',
        ),
        migrations.DeleteModel(
            name='DistributionPlanItem',
        ),
        migrations.DeleteModel(
            name='SupplyPlanItem',
        ),
        migrations.DeleteModel(
            name='WavePlan',
        ),
    ]
