# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0096_auto_20180603_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyplan',
            name='wave_number',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Number of waves'),
        ),
    ]
