# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-05 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0097_auto_20180603_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplanwaveitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waves_items', to='planning.SupplyPlan'),
        ),
    ]
