# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-31 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0009_auto_20180605_1254'),
        ('users', '0004_auto_20180531_0754'),
        ('planning', '0099_auto_20180605_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlySupplyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('to_review', models.BooleanField(default=False)),
                ('reviewed', models.NullBooleanField(default=None)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('to_approve', models.BooleanField(default=False)),
                ('approved', models.NullBooleanField(default=None)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('wave_number', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Number of waves')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Planned by')),
                ('items', models.ManyToManyField(blank=True, to='supplies.SupplyItem')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Section')),
                ('tpm_focal_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='TPM focal point')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
