# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-31 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0100_yearlysupplyplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlysupplyplan',
            name='wave_number',
        ),
    ]
