# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-31 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0101_remove_yearlysupplyplan_wave_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='supply_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_plan', to='planning.YearlySupplyPlan'),
            preserve_default=False,
        ),
    ]
