# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_supplyservice'),
        ('planning', '0102_supplyplan_supply_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='PD Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyItem')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_plan_items', to='planning.YearlySupplyPlan')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyPlanService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.FloatField(blank=True, help_text='$', null=True, verbose_name='Expected Amount')),
                ('quantity', models.PositiveIntegerField(help_text='PD Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyService')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_plan_services', to='planning.YearlySupplyPlan')),
            ],
        ),
    ]
