# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-18 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0103_supplyplanitem_supplyplanservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyplan',
            name='is_for_internal',
            field=models.BooleanField(default=False),
        ),
    ]
