# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-18 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_supplyservice'),
        ('planning', '0104_supplyplan_is_for_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlysupplyplan',
            name='services',
            field=models.ManyToManyField(blank=True, to='supplies.SupplyService'),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='is_for_internal',
            field=models.BooleanField(default=False, verbose_name='Is for Internal use?'),
        ),
    ]
