# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-27 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0105_auto_20190418_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributeditemsite',
            name='tpm_focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='TPM focal point'),
        ),
    ]
