# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_supplyservice'),
        ('planning', '0106_distributeditemsite_tpm_focal_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlysupplyplan',
            name='items',
        ),
        migrations.RemoveField(
            model_name='yearlysupplyplan',
            name='services',
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='services',
            field=models.ManyToManyField(blank=True, to='supplies.SupplyService'),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner Organization'),
        ),
    ]
