# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0107_auto_20190427_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlysupplyplan',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
