# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0108_yearlysupplyplan_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplanwaveitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_distribution_waves', to='supplies.SupplyItem'),
        ),
        migrations.AlterField(
            model_name='supplyplanservice',
            name='expected_amount',
            field=models.FloatField(blank=True, help_text='$', null=True, verbose_name='Expected Amount/Unit Price'),
        ),
    ]
