# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0109_auto_20190502_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='yearly_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yealy_plan', to='planning.YearlySupplyPlan'),
        ),
    ]
