# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='quality_assessment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='quantity_assessment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
