# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0002_auto_20180509_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpmvisit',
            options={'ordering': ['created'], 'verbose_name': 'TPM Visit', 'verbose_name_plural': 'TPM Visits'},
        ),
    ]
