# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0003_auto_20180509_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='distribution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='quantity_distributed',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
