# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0005_auto_20180510_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed', models.CharField(max_length=100, unique=True)),
                ('tpm_visit', models.CharField(max_length=20)),
                ('assessment_slug', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
