# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-14 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0006_assessmenthash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpmvisit',
            options={'ordering': ['created'], 'verbose_name': 'SM Visit', 'verbose_name_plural': 'SM Visits'},
        ),
    ]
