# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-05 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0008_smvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smvisit',
            name='type',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('quality', 'Quality')], max_length=10, null=True),
        ),
    ]
