# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
