# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_notification_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
