# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-19 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backends', '0004_auto_20180519_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
