# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-19 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0006_notification_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
