# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0008_notification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
